packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@picocss/pico": ^2.1.1
  "@types/node": ^24
  astro: 7.0.1
  json-refs: ^3.0.15
  json-schema-to-zod: ^2.8.1
  tsx: ^4.20.5
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: 4.1.9
  zod: ^4.4.3
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
