#:schema ../../packages/schemas/dist/resume.schema.json

[basics]
name = "Neel Shah"
label = "Software Engineer"
location = { city = "New York", region = "NY", countryCode = "US" }
phone = "+17329251305"
email = "neelshah400@gmail.com"
url = "https://www.neelshah.dev"
profiles = [
  { network = "GitHub", username = "neelshah400", url = "https://github.com/neelshah400" },
  { network = "LinkedIn", username = "neelshah400", url = "https://www.linkedin.com/in/neelshah400" },
]

[[work]]
name = "Morgan Stanley"
location = "New York, NY"
position = "Software Engineer II (Associate)"
startDate = "2026-01-01"
highlights = [
  # TODO
]

[[work]]
name = "Morgan Stanley"
location = "New York, NY"
position = "Software Engineer I (Analyst)"
startDate = "2024-08-12"
endDate = "2025-12-31"
highlights = [
  "Designed scalable workflows for loan servicing systems and architected new functionality for high-throughput transaction processing services within Lending, using Angular (TypeScript) for frontend and Spring Boot/Db2 (Java) for backend",
  "Wrote unit/integration tests (JUnit) and created Splunk alerts/metrics to ensure production reliability and prevent regressions",
  "Deployed containerized applications using Docker/Kubernetes with CI/CD pipelines in a Private Cloud environment",
  "Demonstrated the feasibility of leveraging generative AI to eliminate bottlenecks in Origination (via a 90% reduction in manual effort for Operations) through prototyping of integrated document processing workflows, chatbots, graph-based agentic systems, and more (utilizing OCR, vision, structured outputs, tool calling, and various other techniques)",
]

[[work]]
name = "Morgan Stanley"
location = "New York, NY"
position = "Software Engineering Intern (Analyst)"
startDate = "2023-06-05"
endDate = "2023-08-11"
highlights = [
  "Enabled quick analysis of Lending data using complex ML models by developing a versatile, user-friendly platform for model training, evaluation, and inference, using React (TypeScript) for the frontend and Flask/Db2 (Python) for the backend",
  "Supported complex pipelines with preprocessing and feature selection steps as well as hyperparameter tuning via grid search",
  "Prototyped a tool for classifying and extracting information from financial documents using generative AI and OCR models",
]

[[work]]
name = "Capgemini Government Solutions"
location = "McLean, VA"
position = "Technical Intern"
startDate = "2022-06-06"
endDate = "2022-08-19"
highlights = [
  "Reduced processing time by over 80% and enhanced data accuracy by developing a UiPath RPA bot to automate the provisioning of users in Salesforce using data exported weekly from an HR system (previously done manually by the SaaS team)",
  "Presented findings on viability of VR for work to top executives, following hands-on testing and extensive market research",
]

[[work]]
name = "Bloomberg"
location = "Dayton, NJ"
position = "Software Engineering Intern"
startDate = "2021-06-28"
endDate = "2021-08-20"
highlights = [
  "Reduced maintenance downtime for a fleet of 30,000+ servers powering the Bloomberg Terminal by enabling operators to set different retry actions per host on a real-time maintenance operations management dashboard (developed by the Fleet Automation Services team), using Angular (TypeScript) for the frontend and Django/PostgreSQL (Python) for the backend",
  "Containerized the Angular frontend using Docker and improved observability on the Django backend using Grafana",
]

[[work]]
name = "Bloomberg"
location = "Dayton, NJ"
position = "Software Engineering Intern"
startDate = "2020-07-06"
endDate = "2020-08-28"
highlights = [
  "Provided visibility into the efficiency/reliability of maintenance jobs for a fleet of 30,000+ servers powering the Bloomberg Terminal (maintained by the Environment Support Site Reliability Engineering team)",
  "Developed an interactive web application to visualize metrics such as runtime, failure rates, and failure reasons at the host, schedule, and cluster levels, using React (TypeScript) for the frontend and Django/PostgreSQL (Python) for the backend",
]

[[education]]
institution = "University of Maryland"
area = "Computer Science, Minor in Statistics"
studyType = "B.S."
startDate = "2021-08-30"
endDate = "2024-05-22"
score = "4.0/4.0"
location = "College Park, MD"
highlights = [
  "Summa Cum Laude",
  "Dean's List",
  "College Park Scholars: Environment, Technology, & Economy Citation",
  "Teaching Assistant for CMSC131: Object-Oriented Programming I (Jan 2023 — May 2024)",
]

[[projects]]
name = "MenuMuse"
startDate = "2024-05-01"
endDate = "2024-06-30"
url = "https://menumuse.neelshah.dev"
highlights = [
  "Created an AI-powered restaurant search chatbot that you can chat with using natural language to search for restaurants, ask questions, summarize reviews, and more",
  "Built the site using React/Next.js (TypeScript) for the frontend/backend, Google's Gemini 1.5 Flash for chat completions, the Google Maps Platform Places API for restaurant information, and Redis for saving chat history",
]

[[projects]]
name = "NBA Playoff Predictions"
startDate = "2023-01-01"
endDate = "2023-05-31"
url = "https://nba.neelshah.dev"
highlights = [
  "Analyzed the factors influencing teams' playoff success using Python, going through each step of the data science pipeline",
  "Accurately predicted the number of playoff games a given team would win by leveraging regular season data to train 8 different ML models, with the best (a decision tree) achieving a mean deviation of less than 2.5 games",
  "Performed an exhaustive grid search with 5-fold cross-validation to find the optimal parameters for each model",
]

[[skills]]
name = "Programming Languages"
keywords = ["Python", "JavaScript", "TypeScript", "Java", "C#", "Haskell", "OCaml", "C"]

[[skills]]
name = "Web Development"
keywords = [
  "HTML",
  "CSS",
  "React",
  "Angular",
  "FastAPI",
  "Flask",
  "Django",
  "Express",
  "Spring Boot",
  "ASP.NET",
]

[[skills]]
name = "DevOps/Infrastructure"
keywords = ["Linux", "Git", "Docker", "Kubernetes", "CI/CD", "SQL", "Redis", "MongoDB", "Kafka"]

[[skills]]
name = "AI/ML/Automation"
keywords = ["Generative AI", "Data Science", "Machine Learning", "Robotic Process Automation"]
